### PR TITLE
fix rust parts

### PR DESCRIPTION
**Pull request by chris-ha458**
either the type should change or the operator should.
It seems the operator should change and document the setting information for future reference

https://rust-lang.github.io/rust-clippy/master/index.html#/absurd_extreme_comparisons

### CODE REVIEW

**Comment by chris-ha458** [comment]
I would really love a proper contributing.md document styleguide and precommit.

**Comment by chris-ha458** [comment]
I know that `cargo clippy --fix --lib -p dolma` would fix a lot of them automatically but I assumed that the original developers had a reason to have written the code in the first place so I am looking at each item one by one to avoid any unintended changes.

**Comment by soldni** [comment]
@rodneykinney can u take a look? thank you!!

**Comment by chris-ha458** [comment]
I know i've been making more changes since the approval, but unless otherwise stated,
most if not all of the changes are definitely or mostly changes that do not affect behavior and just make the code more idiomatic!

A few that actually change behavior are removing unwrap() as much as possible,
but only when there is a clear and obvious way to address or propagate the error.
As far as I'm concerned they are as suitable for merging as any previous commits, but if there are any that is seen as problematic, let me know.

**Comment by soldni** [comment]
@chris-ha458 looks great! I've merged in.

**Pull request merged**
